name: Build Linux AppImage Qt6 C++

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential ninja-build \
            libgl1-mesa-dev libgles-dev libglib2.0-dev \
            libglib2.0-dev-bin libglvnd-dev libglx-dev \
            libxcb-xinerama0-dev libxcb-icccm4-dev libxcb-image0-dev \
            libxcb-keysyms1-dev libxcb-randr0-dev libxcb-render-util0-dev \
            libxcb-xkb-dev libxkbcommon-x11-dev libfontconfig-dev \
            libfreetype-dev libx11-dev libx11-xcb-dev libxext-dev \
            libxfixes-dev libxi-dev libxrender-dev libxkbcommon-dev \
            libssl-dev wget fuse libfuse2 squashfs-tools cmake git \
            gzip findutils python3-pip --allow-downgrades

      - name: Install Qt 6.10.2
        run: |
          pip install aqtinstall
          aqt install-qt linux desktop 6.10.2 gcc_64 -O $HOME/Qt
          echo "$HOME/Qt/6.10.2/gcc_64/bin" >> $GITHUB_PATH

      - name: Download AppImage Tools
        run: |
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/1-alpha-20251107-1/linuxdeploy-x86_64.AppImage
          wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/1-alpha-20250213-1/linuxdeploy-plugin-qt-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage linuxdeploy-plugin-qt-x86_64.AppImage

      - name: Build unrar library
        run: |
          cd unrar
          make lib

      - name: Build C++ with Qt6
        run: |
          mkdir build
          cd build
          qmake CONFIG+=release ../
          make -j$(nproc)

      - name: Create .desktop file and AppDir Structure
        run: |
          mkdir -p SFDLSaugerPro.AppDir/usr/bin
          mkdir -p SFDLSaugerPro.AppDir/usr/lib
          mkdir -p SFDLSaugerPro.AppDir/usr/share/applications
          mkdir -p SFDLSaugerPro.AppDir/usr/share/icons/hicolor/512x512/apps
          cat << EOF > SFDLSaugerPro.AppDir/usr/share/applications/SFDLSaugerPro.desktop
          [Desktop Entry]
          Name=SFDLSaugerPro
          Exec=SFDLSaugerPro
          Icon=SFDLSaugerPro
          Type=Application
          Categories=Utility;
          EOF
          cp build/SFDLSaugerPro SFDLSaugerPro.AppDir/usr/bin/SFDLSaugerPro
          cp unrar/libunrar.so SFDLSaugerPro.AppDir/usr/lib/libunrar.so
          cp icon.png SFDLSaugerPro.AppDir/usr/share/icons/hicolor/512x512/apps/SFDLSaugerPro.png

      - name: Create AppImage
        run: |
          export QMAKE=$HOME/Qt/6.10.2/gcc_64/bin/qmake
          ./linuxdeploy-x86_64.AppImage \
            --appdir SFDLSaugerPro.AppDir \
            --executable SFDLSaugerPro.AppDir/usr/bin/SFDLSaugerPro \
            --plugin qt \
            --output appimage

      - name: Upload AppImage as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SFDLSaugerPro.AppImage
          path: 'SFDLSaugerPro*.AppImage'
