name: C++ Qt5 Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Qt5
        run: |
          brew update
          brew install qt@5
          brew link qt@5 --force

      - name: Debug Qt5 Installation
        run: |
          echo "Checking Qt5 installation..."
          ls -l /usr/local/opt/qt@5/bin || true
          ls -l /opt/homebrew/opt/qt@5/bin || true
          which qmake
          qmake --version || true

      - name: Set up Xcode command-line tools
        run: |
          sudo xcode-select --switch /Applications/Xcode.app
          xcode-select --install || true

      - name: Build ftplib
        run: |
          git clone https://github.com/DoctorW00/qtftp.git
          cd qtftp
          /opt/homebrew/opt/qt@5/bin/qmake || /usr/local/opt/qt@5/bin/qmake
          make
          sudo make install

      - name: Build unrar library
        run: |
          cd unrar
          make lib
          ls -la

      - name: Build C++ with Qt5
        run: |
          mkdir build
          cd build
          /opt/homebrew/opt/qt@5/bin/qmake ../ || /usr/local/opt/qt@5/bin/qmake ../
          make

      - name: Copy unrar lib to SFDLSaugerPro.app
        run: |
          mkdir -p build/SFDLSaugerPro.app/Contents/Frameworks/
          cp unrar/libunrar.so build/SFDLSaugerPro.app/Contents/Frameworks/libunrar.so || true

      - name: Use macdeployqt to deploy the app
        run: |
          /opt/homebrew/opt/qt@5/bin/macdeployqt build/SFDLSaugerPro.app || /usr/local/opt/qt@5/bin/macdeployqt build/SFDLSaugerPro.app

      - name: Sign the app bundle
        run: |
          codesign --force --deep --sign "-" build/SFDLSaugerPro.app
          codesign -dv --verbose=4 build/SFDLSaugerPro.app || true
          find build/SFDLSaugerPro.app/Contents -name "*.dylib" -o -name "*.so" | while read lib; do
            codesign --force --sign "-" "$lib" || true
          done

      - name: Create DMG package
        run: |
          hdiutil create -volname "SFDLSaugerPro" -srcfolder build/SFDLSaugerPro.app -ov -format UDZO build/SFDLSaugerPro.dmg
          codesign --force --sign "-" build/SFDLSaugerPro.dmg

      - name: Upload .dmg Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-dmg
          path: build/SFDLSaugerPro.dmg
