name: C++ Qt5 Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Qt5
        run: |
          brew update
          brew install qt@5
          brew link qt@5 --force

      - name: Debug Qt5 Installation
        run: |
          echo "Checking Qt5 installation..."
          ls -l /usr/local/opt/qt@5/bin || true
          ls -l /opt/homebrew/opt/qt@5/bin || true
          which qmake
          qmake --version || true

      - name: Set up Xcode command-line tools
        run: |
          sudo xcode-select --switch /Applications/Xcode.app
          xcode-select --install || true

      - name: Build ftplib
        run: |
          git clone https://github.com/DoctorW00/qtftp.git
          cd qtftp
          /opt/homebrew/opt/qt@5/bin/qmake || /usr/local/opt/qt@5/bin/qmake
          make
          sudo make install

      - name: Build unrar library
        run: |
          cd unrar
          make lib
          sudo make install-lib
          sudo mkdir -p /usr/local/lib
          sudo cp libunrar.dylib /usr/local/lib/ || true
          sudo cp unrar.hpp /usr/local/include/ || true
          sudo ln -sf /usr/local/lib/libunrar.dylib /usr/local/lib/libunrar.so || true

      - name: Build C++ with Qt5
        run: |
          mkdir build
          cd build
          /opt/homebrew/opt/qt@5/bin/qmake ../ || /usr/local/opt/qt@5/bin/qmake ../
          make

      - name: Copy unrar lib to SFDLSaugerPro.app
        run: |
          mkdir -p build/SFDLSaugerPro.app/Contents/Frameworks/
          cp /usr/local/lib/libunrar.dylib build/SFDLSaugerPro.app/Contents/Frameworks/ || cp /usr/lib/libunrar.dylib build/SFDLSaugerPro.app/Contents/Frameworks/ || true
          cp /usr/local/lib/libunrar.so build/SFDLSaugerPro.app/Contents/Frameworks/ || ln -sf libunrar.dylib build/SFDLSaugerPro.app/Contents/Frameworks/libunrar.so
          install_name_tool -change /usr/local/lib/libunrar.dylib @executable_path/../Frameworks/libunrar.dylib build/SFDLSaugerPro.app/Contents/MacOS/SFDLSaugerPro || true
          install_name_tool -change /usr/lib/libunrar.dylib @executable_path/../Frameworks/libunrar.dylib build/SFDLSaugerPro.app/Contents/MacOS/SFDLSaugerPro || true
          install_name_tool -change /usr/local/lib/libunrar.so @executable_path/../Frameworks/libunrar.so build/SFDLSaugerPro.app/Contents/MacOS/SFDLSaugerPro || true

      - name: Use macdeployqt to deploy the app
        run: |
          /opt/homebrew/opt/qt@5/bin/macdeployqt build/SFDLSaugerPro.app -dmg || /usr/local/opt/qt@5/bin/macdeployqt build/SFDLSaugerPro.app -dmg

      - name: Upload .dmg Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-dmg
          path: build/SFDLSaugerPro.dmg
